name: Continuous Deployment

on:
  push:
    branches: ['main']
    paths-ignore: ['docs/**']

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/run-build.yml
    with:
      # Note: must match image_tag set in deploy step
      image_tag: latest
      should_publish: true

  test:
    uses: ./.github/workflows/run-test.yml

  deploy:
    needs: ['test', 'build']
    uses: ./.github/workflows/run-deploy.yml
    with:
      environment: integration
      # Note: must match image_tag set in build step
      image_tag: latest
