name: Continuous Deployment

on:
  push:
    branches: ['main']
    paths-ignore: ['docs/**']

permissions:
  contents: read
  id-token: write

env:
  IMAGE_TAG: latest

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/run-build.yml
    with:
      image_tag: ${{ env.IMAGE_TAG }}
      should_publish: 'true'

  test:
    uses: ./.github/workflows/run-test.yml

  deploy:
    needs: ['test', 'build']
    uses: ./.github/workflows/run-deploy.yml
    with:
      environment: integration
      image_tag: ${{ env.IMAGE_TAG }}
