name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['main']
    paths-ignore: ['docs/**']

  push:
    branches: ['main']
    paths-ignore: ['docs/**']

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - run: corepack enable

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: 'true'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: 'true'

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install python dependencies
        run: uv sync --locked

      # Yarn is specified as our packageManager in package.json.
      - run: corepack enable

      - name: Set up node
        # v5 now has automatic caching: https://github.com/actions/setup-node/releases/v5.0.0
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: 'package.json'

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      # TODO-WF: this could be cached https://github.com/microsoft/playwright/issues/7249
      - name: Install playwright browser
        run: uv run playwright install

      - name: Check db migrations
        run: uv run python manage.py makemigrations --check

      - name: Run db migrations
        run: uv run python manage.py migrate

      - name: Test with pytest
        run: uv run pytest

  docker:
    runs-on: ubuntu-latest
    needs: [linter, pytest] # TODO-NG: this serializes the build. could we make only the `push` dependent?

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          role-to-assume: arn:aws:iam::153784117502:role/deploy-sandwich-ci
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sandwich
          IMAGE_TAG: latest
        run: >
          docker buildx build .
          --builder ${{ steps.buildx.outputs.name }}
          --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG
          --cache-from type=registry,ref=$REGISTRY/$REPOSITORY:cache
          --cache-to mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=$REGISTRY/$REPOSITORY:cache
          $(test "${{ github.ref }}" = "refs/heads/main" && echo "--push")
