name: run-build.yml

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'the tag to apply to the docker image'
        required: false
        type: string
        default: ${{ github.sha }}
      should_publish:
        description: 'Whether to publish the image to the registry'
        required: false
        type: boolean
        default: false

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: arn:aws:iam::153784117502:role/deploy-sandwich-ci
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sandwich
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: >
          docker buildx build .
          --builder ${{ steps.buildx.outputs.name }}
          --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG
          --cache-from type=registry,ref=$REGISTRY/$REPOSITORY:cache
          --cache-to mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=$REGISTRY/$REPOSITORY:cache
          --output type=docker

      - name: Publish image to registry
        if: ${{ inputs.should_publish }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sandwich
          IMAGE_TAG: latest
        run: >
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
