name: run-deploy.yml

on:
  workflow_call:
    inputs:
      app:
        description: 'name of the service to be deployed'
        required: false
        type: string
        default: sandwich
      environment:
        description: 'name of the deployment environment (integration, etc)'
        required: true
        type: string
      image_tag:
        description: 'docker image tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          # Defined in tf: https://github.com/thrivehealth/terraform/blob/main/stacks/deploy/sandwich.tf
          role-to-assume: arn:aws:iam::153784117502:role/deploy-sandwich-ci
          aws-region: ca-central-1
      - env:
          APP: sandwich
          ENVIRONMENT: ${{ inputs.environment }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: ./scripts/deploy.sh ${{ inputs.app }}
