name: run-test.yml

on:
  workflow_call:
    inputs:
      environment:
        description: 'name of the smoke test environment (integration, etc)'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: 'true'

      - name: Set up python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version-file: '.python-version'

      - name: Run the smoke test
        run: make smoke-test-${{ inputs.environment }}
