name: run-test.yml

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install uv
        uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: 'true'

      - name: Set up python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version-file: '.python-version'

      - name: Install python dependencies
        run: uv sync --locked

      # Yarn is specified as our packageManager in package.json.
      - run: corepack enable

      - name: Set up node
        # v5 now has automatic caching: https://github.com/actions/setup-node/releases/v5.0.0
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: 'package.json'

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Check db migrations
        run: uv run python manage.py makemigrations --check

      - name: Run the tests
        run: make test
